(function () {
  "use strict";

  // storage.js separates two ideas: shared defaults live in a .game.json file,
  // while browser local storage holds one student's draft changes.

  const levelKey = "platformer-lab-levels-v1";
  const spriteKey = "platformer-lab-sprites-v1";
  const gameNameKey = "platformer-lab-game-name-v1";
  const gameDataFormat = "platformer-lab-game-data";
  const gameDataVersion = 1;

  let activeDefaultGameData = null;

  function clone(value) {
    return window.PixelArt.clone(value);
  }

  function loadJson(key) {
    try {
      const raw = window.localStorage.getItem(key);
      return raw ? JSON.parse(raw) : null;
    } catch (error) {
      console.warn("Could not load saved data", error);
      return null;
    }
  }

  function saveJson(key, value) {
    window.localStorage.setItem(key, JSON.stringify(value));
  }

  function slugify(value) {
    return String(value || "")
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "game-data";
  }

  function normalizeLevel(level) {
    const defaults = window.PlatformerDefaults;
    const source = level && typeof level === "object" ? level : {};
    const width = Math.max(8, Number(source.width) || 32);
    const height = Math.max(8, Number(source.height) || 17);
    const tiles = Array.from({ length: height }, (_, row) => {
      const sourceRow = Array.isArray(source.tiles) ? source.tiles[row] : [];
      return Array.from({ length: width }, (_, col) => Number(sourceRow && sourceRow[col]) || 0);
    });

    return {
      name: String(source.name || "Untitled Level").slice(0, 48),
      width,
      height,
      tileSize: defaults.tileSize,
      tiles,
      objects: Array.isArray(source.objects) ? source.objects.map((object) => ({ ...object })) : []
    };
  }

  function fallbackGameData() {
    return window.PlatformerDefaults.createDefaultGameData();
  }

  function defaultGameData() {
    return activeDefaultGameData || normalizeGameData(fallbackGameData());
  }

  function normalizeGameData(gameData) {
    // Game data files are allowed to be imperfect while students experiment.
    // Normalize makes the engine receive predictable arrays, sizes, and names.
    const fallback = fallbackGameData();
    const source = gameData && typeof gameData === "object" ? gameData : fallback;
    const sourceLevels = Array.isArray(source.levels) && source.levels.length > 0 ? source.levels : fallback.levels;
    const sourceSprites = source.sprites && typeof source.sprites === "object" ? source.sprites : fallback.sprites;

    return {
      format: gameDataFormat,
      version: gameDataVersion,
      name: String(source.name || fallback.name || window.PlatformerDefaults.defaultGameName).slice(0, 64),
      levels: sourceLevels.map(normalizeLevel),
      sprites: window.PixelArt.normalizeSprites(sourceSprites)
    };
  }

  async function loadDefaultGameData(source) {
    // A static site has no database, so the shared starting point is fetched as
    // a plain JSON file generated by tools/build-game-data.js.
    const fallback = normalizeGameData(fallbackGameData());
    if (!source) {
      return fallback;
    }

    try {
      const response = await window.fetch(source, { cache: "no-cache" });
      if (!response.ok) {
        throw new Error(`Could not load ${source}: ${response.status}`);
      }
      return normalizeGameData(await response.json());
    } catch (error) {
      console.warn("Could not load game data file; using built-in defaults", error);
      return fallback;
    }
  }

  function loadLevels(defaultLevels) {
    const saved = loadJson(levelKey);
    if (Array.isArray(saved) && saved.length > 0) {
      return saved.map(normalizeLevel);
    }
    const levels = Array.isArray(defaultLevels) ? defaultLevels : defaultGameData().levels;
    return levels.map(normalizeLevel);
  }

  function saveLevels(levels) {
    saveJson(levelKey, levels.map(normalizeLevel));
  }

  function loadSprites(defaultSprites) {
    const saved = loadJson(spriteKey);
    if (saved && typeof saved === "object") {
      return window.PixelArt.normalizeSprites(saved);
    }
    const sprites = defaultSprites && typeof defaultSprites === "object" ? defaultSprites : defaultGameData().sprites;
    return window.PixelArt.normalizeSprites(clone(sprites));
  }

  function saveSprites(sprites) {
    saveJson(spriteKey, window.PixelArt.normalizeSprites(sprites));
  }

  function resetLevels() {
    window.localStorage.removeItem(levelKey);
    return loadLevels();
  }

  function resetSprites() {
    window.localStorage.removeItem(spriteKey);
    return loadSprites();
  }

  async function loadGameData(source) {
    // Load order matters: first choose the project default, then layer any local
    // browser drafts on top for this user only.
    activeDefaultGameData = await loadDefaultGameData(source);
    const savedName = loadJson(gameNameKey);
    return {
      name: typeof savedName === "string" && savedName.trim() ? savedName.trim() : activeDefaultGameData.name,
      levels: loadLevels(activeDefaultGameData.levels),
      sprites: loadSprites(activeDefaultGameData.sprites)
    };
  }

  function saveGameName(name) {
    const normalizedName = String(name || "").trim().slice(0, 64);
    saveJson(gameNameKey, normalizedName || defaultGameData().name);
  }

  function makeGameData(name, levels, sprites) {
    return normalizeGameData({
      name: String(name || "").trim() || defaultGameData().name,
      levels,
      sprites
    });
  }

  function downloadGameData(name, levels, sprites) {
    // The in-browser Build Game Data button creates a portable file. The CLI
    // build command can later install that file as the project default.
    const gameData = makeGameData(name, levels, sprites);
    saveGameName(gameData.name);
    downloadJson(`${slugify(gameData.name)}.game.json`, gameData);
    return gameData;
  }

  async function buildGameData(name, levels, sprites) {
    // When tools/dev-server.js is serving the app, this saves straight into the
    // repo. On any plain static server, the request fails and we download a file.
    const gameData = makeGameData(name, levels, sprites);
    saveGameName(gameData.name);

    try {
      const response = await window.fetch("/api/game-data", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ gameData })
      });

      if (response.ok) {
        const result = await response.json();
        return {
          gameData,
          savedToProject: true,
          path: result.path || "assets/game-data/"
        };
      }
    } catch (error) {
      // A missing endpoint just means the app is running from a normal static
      // server. Downloading keeps the workflow usable everywhere.
    }

    downloadJson(`${slugify(gameData.name)}.game.json`, gameData);
    return {
      gameData,
      savedToProject: false,
      path: `${slugify(gameData.name)}.game.json`
    };
  }

  function downloadJson(filename, data) {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(link.href);
  }

  function readJsonFile(file, onLoaded, onError) {
    const reader = new FileReader();
    reader.addEventListener("load", () => {
      try {
        onLoaded(JSON.parse(String(reader.result)));
      } catch (error) {
        if (onError) {
          onError(error);
        }
      }
    });
    reader.addEventListener("error", () => {
      if (onError) {
        onError(reader.error);
      }
    });
    reader.readAsText(file);
  }

  window.PlatformerStorage = {
    clone,
    normalizeGameData,
    normalizeLevel,
    loadGameData,
    loadLevels,
    saveLevels,
    resetLevels,
    loadSprites,
    saveSprites,
    resetSprites,
    saveGameName,
    makeGameData,
    downloadGameData,
    buildGameData,
    downloadJson,
    readJsonFile
  };
})();